export const TODOS_SUCCESS = 'TODOS_SUCCESS'
export const TODOS_FAIL = 'TODOS_FAIL'
export const TODOS_REQUEST = 'TODOS_REQUEST'

export const COMPLETED_TODOS_SUCCESS = 'COMPLETED_TODOS_SUCCESS'
export const COMPLETED_TODOS_FAIL = 'COMPLETED_TODOS_FAIL'
export const COMPLETED_TODOS_REQUEST = 'COMPLETED_TODOS_REQUEST'

export const CREATE_TODOS_SUCCESS = 'CREATE_TODOS_SUCCESS'
export const CREATE_TODOS_FAIL = 'CREATE_TODOS_FAIL'
export const CREATE_TODOS_REQUEST = 'CREATE_TODOS_REQUEST'

export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS'
export const DELETE_TODOS_FAIL = 'DELETE_TODOS_FAIL'
export const DELETE_TODOS_REQUEST = 'DELETE_TODOS_REQUEST'